CREATE TABLE SIMPLE1 (ID_SIMPLE INTEGER,EDAD INTEGER, NOMBRES VARCHAR2(40));
-- lA LLENAMOS CON INFORMACION RAPIDA
DECLARE
MI_EDAD INTEGER;
BEGIN
MI_EDAD:=19;
FOR I IN 1..20 LOOP
MI_EDAD:=MI_EDAD+I;
INSERT INTO SIMPLE1 VALUES(I,MI_EDAD,'ALEJANDRA');
END LOOP;
END;
/

-- HACER UN SELECT_ SELECT *FROM SIMPLE1;

select * from simple1;

UPDATE simple1 SET NOMBRE='XXX' WHERE ID=21;
SET SERVEROUTPUT ON;
DECLARE
MI_NOMBRE VARCHAR2(40);
BEGIN
SELECT NOMBRE INTO MI_NOMBRE FROM SIMPLE1 WHERE EDAD=21;
DBMS_OUTPUT.PUT_LINE(MI_NOMBRE);
END;
/
SELECT * FROM SIMPLE1;
DELETE FROM SIMPLE1;
INSERT INTO SIMPLE1 VALUES(1,21,'JUAN');
INSERT INTO SIMPLE1 VALUES(2,23,'ANA');
INSERT INTO SIMPLE1 VALUES(3,25,'PEDRO');
