CREATE OR REPLACE PROCEDURE GUARDAR_PELICULA 
(
  MY_ID_PELICULA OUT NUMBER  
, MY_TITULO IN VARCHAR2  
, MY_SINOPSIS IN VARCHAR2  
, MY_CLASIFICACION IN VARCHAR2  
) AS 
BEGIN
SELECT SEC_PELICULA.NEXTVAL INTO MY_ID_PELICULA FROM DUAL;
INSERT INTO PELICULA VALUES(MY_ID_PELICULA,MY_TITULO,MY_SINOPSIS,MY_CLASIFICACION);


  NULL;
END GUARDAR_PELICULA;
DECLARE
VALOR INTEGER;
BEGIN
guardar_pelicula(VALOR,'EL RENACIDO','ESTA PUES MAS O MENOS','B15');
END;
/
SELECT * FROM PELICULA;



suma
CREATE OR REPLACE PROCEDURE SUMA 
(PRIMERO IN NUMBER , SEGUNDO IN NUMBER , RESULTADO OUT NUMBER) AS 
BEGIN
  RESULTADO:=PRIMERO+SEGUNDO;
END SUMA;




create or replace 
procedure hola_mundo( nombre IN VARCHAR2)
AS
BEGIN
--AQUI VA LA LOGICA
DBMS_OUTPUT.PUT_LINE('HOLA COMO ESTAS' ||NOMBRE);
END;
